/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package base-4.1.0.0 */
#define MIN_VERSION_base(major1,major2,minor) \
  (major1) <  4 || \
  (major1) == 4 && (major2) <  1 || \
  (major1) == 4 && (major2) == 1 && (minor) <= 0

/* package bytestring-0.9.1.5 */
#define MIN_VERSION_bytestring(major1,major2,minor) \
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 1

/* package fingertree-0.0.1.0 */
#define MIN_VERSION_fingertree(major1,major2,minor) \
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 1

/* package utf8-string-0.3.5 */
#define MIN_VERSION_utf8_string(major1,major2,minor) \
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 5

