#!/bin/sh
ghci -XCPP -XEmptyDataDecls -XFlexibleContexts -XFlexibleInstances -XFunctionalDependencies -XMultiParamTypeClasses -XTypeFamilies -XTypeSynonymInstances -XUndecidableInstances -XGADTs Control.Category.Classes Control.Category.Dual $*
